apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2022-12-03T04:19:27Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: postgresql
    release: wiki
    role: master
  name: data-wiki-postgresql-0
  namespace: wiki
  resourceVersion: "7325742"
  uid: d521b59d-9034-45a0-b8f8-0f936525dc5a
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
status:
  phase: Pending
