---
name: Create helm chart release
on: 
  pull_request:
    types: [closed]
  push:
    branches: 
    - main
jobs:
  version: 
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ env.VERSION }}
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Extract version from Chart.yaml
      run: echo "VERSION=$(cat Chart.yaml | grep -m 1 ^version:| awk '{print $2}')" >> $GITHUB_ENV
  publish:
    runs-on: ubuntu-latest
    needs: [version]
    steps: 
    - name: Create release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ needs.version.outputs.version }}
        release_name: ${{ needs.version.outputs.version }}
        body: New release based on an updated chart version (${{ needs.version.outputs.version }})  pulled from requarks/wiki. 
        draft: false
        prerelease: false
        
   
     
